id: IABB7E6A2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T20:58:59+00:00'
last_modified: '2022-06-07T16:10:27.686483+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17272
  title: སེང་གདོང་མའི་མངོན་རྟོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E155:
      image_group_id: I8LS17295
      title: ''
      total_pages: 96
      order: 1
      base_file: E155.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
