id: P002916
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS17272
  title: སེང་གདོང་མའི་མངོན་རྟོགས།
  author: ''
  volumes:
    7f0aabc2a97d40459d4fc066246fa8b9:
      image_group_id: I8LS17295
      title: ''
      volume_number: 1
      total_pages: 96
      base_file: v001.txt
