id: P002916
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS17272
  title: སེང་གདོང་མའི་མངོན་རྟོགས།
  author: ''
  volumes:
    7f0aabc2a97d40459d4fc066246fa8b9:
      image_group_id: I8LS17295
      title: ''
      volume_number: 1
      total_pages: 96
